In [1]:
import mysql.connector

In [2]:
mydb = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Veera@123",
    database="mydatabase1"
    
)
# creating a cursor

mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")
for i in mycursor:
    print(i)

('data_employee',)
('information_schema',)
('mydatabase1',)
('mysql',)
('performance_schema',)
('sales',)
('sys',)

In [4]:
query_u = "USE data_employee"
mycursor.execute(query_u)
mycursor.execute("SHOW TABLES")
for i in mycursor:
    print(i)

('customer_table',)
('customer_view',)
('department_dataset',)
('employee',)
('employee_table',)

# Data inside two tables

In [6]:
mycursor.execute("SELECT * FROM department_dataset limit 10")
for i in mycursor:
    print(i)
print("---------")
mycursor.execute("SELECT * from employee limit 10")
for i in mycursor:
    print(i)

(1, 'HR', 'Pune', 'yes', 10000)
(2, 'Finance', 'Bangalore', 'no', 15000)
(3, 'Finance', 'Bangalore', 'no', 18000)
(4, 'Finance', 'Pune', 'no', 10000)
(5, 'Tech', 'Mumbai', 'no', 10000)
(6, 'Tech', 'Pune', 'no', 10000)
(7, 'Tech', 'Bangalore', 'yes', 18000)
(8, 'HR', 'Bangalore', 'no', 18000)
(9, 'HR', 'Pune', 'no', 10000)
(10, 'HR', 'Pune', 'no', 10000)
---------
(2, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 1500)

# JOIN

In [7]:
query_j = "SELECT * from department_dataset join employee on employee.location = department_dataset.location"
mycursor.execute(query_j)
for i in mycursor:
    print(i)

(35, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(37, 'Data Analyst', 'chennai', 'yes', 30000, 36, 'Data Analyst', 'chennai', 'yes', 3000)
(36, 'Data Analyst', 'chennai', 'yes', 30000, 36, 'Data Analyst', 'chennai', 'yes', 3000)
(37, 'Data Analyst', 'chennai', 'yes', 30000, 37, 'Data Analyst', 'chennai', 'yes', 3000)
(36, 'Data Analyst', 'chennai', 'yes', 30000, 37, 'Data Analyst', 'chennai', 'yes', 3000)
(35, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)

# Inner join

In [13]:
query_j = "SELECT department_dataset.id,department_dataset.dept_name , department_dataset.salary from department_dataset left join employee on employee.location = department_dataset.location"
mycursor.execute(query_j)
for i in mycursor:
    print(i)

(1, 'HR', 10000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(2, 'Finance', 15000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(3, 'Finance', 18000)
(4, 'Finance', 10000)
(5, 'Tech', 10000)
(6, 'Tech', 10000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(7, 'Tech', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(8, 'HR', 18000)
(9, 'HR', 10000)
(10, 'HR', 10000)
(11, 'HR', 10000)
(12, 'HR', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(13, 'Finance', 18000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(14, 'Tech', 15000)
(15, 'Tech', 10000)
(16, 'Tech', 10000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(17, 'Tech', 15000)
(18, 'Finance', 10000)
(19, 'HR', 10000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(20, 'Finance', 15000)
(21, 'Tech', 10000)
(22, 'Tech', 10000)
(23, 'Tech', 10000)
(24, 'Tech', 10000)
(25, 'Finance', 10000)
(26, 'HR', 10000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(27, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(28, 'HR', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(29, 'Finance', 15000)
(30, 'Finance', 10000)
(31, 'Tech', 10000)
(32, 'Tech', 10000)
(33, 'HR', 10000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(34, 'HR', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(35, 'Tech', 15000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(36, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)
(37, 'Data Analyst', 30000)

# Right Join

In [10]:
query_j = "SELECT * from department_dataset right join employee on employee.location = department_dataset.location"
mycursor.execute(query_j)
for i in mycursor:
    print(i)

(35, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 17, 'Tech', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 20, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 20, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 27, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 27, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 28, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 28, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 29, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 29, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 34, 'HR', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 34, 'HR', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 35, 'Tech', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 35, 'Tech', 'Bangalore', 'no', 1500)
(37, 'Data Analyst', 'chennai', 'yes', 30000, 36, 'Data Analyst', 'chennai', 'yes', 3000)
(36, 'Data Analyst', 'chennai', 'yes', 30000, 36, 'Data Analyst', 'chennai', 'yes', 3000)
(37, 'Data Analyst', 'chennai', 'yes', 30000, 37, 'Data Analyst', 'chennai', 'yes', 3000)
(36, 'Data Analyst', 'chennai', 'yes', 30000, 37, 'Data Analyst', 'chennai', 'yes', 3000)
(35, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 2, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 2, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 3, 'Finance', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 3, 'Finance', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 7, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 8, 'HR', 'Bangalore', 'no', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 8, 'HR', 'Bangalore', 'no', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 13, 'Finance', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(14, 'Tech', 'Bangalore', 'yes', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(13, 'Finance', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(8, 'HR', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(7, 'Tech', 'Bangalore', 'yes', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(3, 'Finance', 'Bangalore', 'no', 18000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(2, 'Finance', 'Bangalore', 'no', 15000, 14, 'Tech', 'Bangalore', 'yes', 1500)
(35, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(34, 'HR', 'Bangalore', 'yes', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(29, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(28, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(27, 'HR', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(20, 'Finance', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)
(17, 'Tech', 'Bangalore', 'no', 15000, 17, 'Tech', 'Bangalore', 'no', 1500)